### ISSUE TITLE
output is always gray

### ISSUE THREAD

**Issue by sugizo** [amirho3einsedaghati/pyimkernel#1]
**env** 
google colab

**code**
```
!wget -c 'https://i.ytimg.com/vi/vEYsdh6uiS4/maxresdefault.jpg'
pip install -U pyimkernel IPython
from pyimkernel import ApplyKernels
import cv2
import IPython
IPython.display.Image('maxresdefault.jpg')
# Create an instance
imkernel = ApplyKernels(random_seed = 0)
blur = imkernel.apply_filter_on_color_img(img, kernel_name = 'blur', with_resize = True, dsize = (100, 100) )
imkernel.imshow(image = blur, figsize = (7, 7) )
```

**result**
![image](https://github.com/amirho3einsedaghati/pyimkernel/assets/2418295/8dd040b4-5370-4c8b-94e2-018fe8fba4d1)

**expected result**
got the blur image with color 

**question**
tried different kernel_name = 'blur', box blur, sharpen, soften
but 
got the same result (gray output)

why output is always gray ?

best regards

**Comment by amirho3einsedaghati** [comment]
Hi, Thanks a lot for your report.

There are some mistakes in my code, I'll fix this issue in the future version (0.9.0).

best regards @sugizo
