### ISSUE TITLE
resize feature on image manipulation

### ISSUE THREAD

**Issue by sugizo** [amirho3einsedaghati/pyimkernel#10]
nice to have resize feature on image manipulation
**e.g.**
`grayscale = manipulation.grayscale(Image.fromarray(image), with_resize = True, dsize = (100, 100) )`
or
`soft_light = manipulation.soft_light(image1, image2, with_resize = True, dsize = (100, 100) )`

thanks and best regards

**Comment by amirho3einsedaghati** [comment]
Thanks for your suggestion, maybe I'll add it in the future version, but I wanna stop developing the Pyimkernel package for now because I'm so busy and have a lot of work to do. I think the project has reached a good level and without adding this feature can work very well.
