### ISSUE TITLE
output is not expected (no error occured)

### ISSUE THREAD

**Issue by sugizo** [amirho3einsedaghati/pyimkernel#2]
**env** 
google colab

**code**
```
sharpen = imkernel.apply_filter_on_color_img(img, kernel_name = 'sharpen', with_resize = True)
imkernel.imshow(image = sharpen, figsize = (3, 3) )
cv2.imwrite('sharpen.png', sharpen)
IPython.display.Image('sharpen.png')
```

**result is not expected**
tested with unsharp masking and soften got the same result (have the yellow line)
![image](https://github.com/amirho3einsedaghati/pyimkernel/assets/2418295/46544e55-ba05-4d70-b928-9f8de962d0ef)

**expected result like using opencv kernel**
![image](https://github.com/amirho3einsedaghati/pyimkernel/assets/2418295/b5d5e7ee-0475-49fa-9c7a-c08e8d7178ad)

my expectation from this python module is 
user dont have to define the kernel, 
because developer already define it, so that user just call the function, 
but 
tested above, prove my expectation is wrong

best regards

**Comment by amirho3einsedaghati** [comment]
Thanks a bunch for mentioning this issue, I'll fix it for sure as soon as posible.

best regards @sugizo
