### ISSUE TITLE
add kernel from wiki 

### ISSUE THREAD

**Issue by sugizo** [amirho3einsedaghati/pyimkernel#4]
![image](https://github.com/amirho3einsedaghati/pyimkernel/assets/2418295/a4d28e88-6dc6-4c02-8743-7a841311a2ef)

**ref**
https://en.wikipedia.org/wiki/Kernel_(image_processing)

e.g.
```
# Ridge or Edge Detection1
kernel0 = np.array([[0, -1, 0],
                    [-1, 4, -1],
                    [0, -1, 0] ] )

# Ridge or Edge Detection2
kernel0 = np.array([[-1, -1, -1],
                    [-1, 8, -1],
                    [-1, -1, -1] ] )

# Box Blur
kernel0 = (1 / 9.0) * np.array([[1, 1, 1],
                                [1, 1, 1],
                                [1, 1, 1] ] )

# Gaussian Blur 3x3
kernel0 = (1 / 16.0) * np.array([[1, 2, 1],
                                 [2, 4, 2],
                                 [1, 2, 1] ] )

# Gaussian Blur 5x5
kernel0 = (1 / 256.0) * np.array([[1, 4, 6, 4, 1],
                                  [4, 16, 24, 16, 4],
                                  [6, 24, 36, 24, 6],
                                  [4, 16, 24, 16, 4],
                                  [1, 4, 6, 4, 1] ] )
```
or whatever that is not given on code above

thanks and best regards

**Comment by amirho3einsedaghati** [comment]
I have no idea how to access all of the image kernels published on the Internet, however, I can use Wikipedia to add other kernels that are not in my package.

best regards @sugizo

**Comment by sugizo** [comment]
not sure where you got the kernel value in ur package, 

just comparison, this is the detail explanation (more clear than wiki)
all in 3x3 matrix, while in wiki there are 5x5 matrix too
and 
some is the rename (outline = edge)

**ref**
https://setosa.io/ev/image-kernels

best regards

**Comment by amirho3einsedaghati** [comment]
Actually, I used the Setosa website and ChatGPT to gather kernel values and utilized other websites to ensure that the information I collected was accurate and properly attributed.

Ok, I will try to collect their 5x5 matrices and then add them to the package like something there is in Wikipedia.

best regards @sugizo

**Comment by sugizo** [comment]
**suggestion** 
put custom kernel too in this python module, 
just like in setosa.io there is custom kernel 
so that user can input whatever value they want

**e.g.**
```
custom = np.array([[0, 1, 0],
                   [1, 9, 1],
                   [0, 1, 0] ] )

custom= imkernel.apply_filter_on_color_img(image, kernel_name = custom)
```

thanks and best regards

**Comment by amirho3einsedaghati** [comment]
Thank you for mentioning it. I'll add this too in the next version.

Best Regards @sugizo
